// src/Modules/Organization/OrganizationDTO.ts

export {
  createBranchSchema,
  updateBranchSchema,
  assignBranchManagerSchema,
  createDepartmentSchema,
  updateDepartmentSchema,
  assignDepartmentManagerSchema,
  createRoleSchema,
  updateRoleSchema,
  saveRolePermissionsSchema,
  createDesignationSchema,
  updateDesignationSchema,
  permissionAssignmentItemSchema,
  type CreateBranchDTO,
  type UpdateBranchDTO,
  type AssignBranchManagerDTO,
  type BranchItem,
  type BranchManagerItem,
  type BranchStats,
  type BranchWithCapabilities,
  type CreateDepartmentDTO,
  type UpdateDepartmentDTO,
  type AssignDepartmentManagerDTO,
  type CreateRoleDTO,
  type UpdateRoleDTO,
  type SaveRolePermissionsDTO,
  type CreateDesignationDTO,
  type UpdateDesignationDTO,
  type DepartmentItem,
  type DepartmentManagerItem,
  type RoleItem,
  type RoleDetailItem,
  type DesignationItem,
  type OrgNodeType,
  type UnifiedOrgNode,
  type OrganizationStructureResponse,
} from "@workspace/shared";
