// src/Modules/Organization/OrganizationDTO.ts

export {
  createDepartmentSchema,
  updateDepartmentSchema,
  assignDepartmentManagerSchema,
  createRoleSchema,
  updateRoleSchema,
  saveRolePermissionsSchema,
  createDesignationSchema,
  updateDesignationSchema,
  permissionAssignmentItemSchema,
  type CreateDepartmentDTO,
  type UpdateDepartmentDTO,
  type AssignDepartmentManagerDTO,
  type CreateRoleDTO,
  type UpdateRoleDTO,
  type SaveRolePermissionsDTO,
  type CreateDesignationDTO,
  type UpdateDesignationDTO,
  type DepartmentItem,
  type DepartmentManagerItem,
  type RoleItem,
  type RoleDetailItem,
  type DesignationItem,
} from "@workspace/shared";
