import type { ProjectWorkspaceItem, ChatMessage, WorkspaceMember } from "./types";

export const mockCurrentUser: WorkspaceMember = {
  id: "user-current",
  name: "Fiamanillah",
  email: "admin@softvence.com",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  designation: "Principal Tech Lead",
  role: "Tech Lead",
  department: "Engineering",
  shift: "Day (09:00 - 18:00)",
  isOnline: true,
};

export const memberSarah: WorkspaceMember = {
  id: "user-1",
  name: "Sarah Chen",
  email: "sarah.chen@softvence.com",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  designation: "Lead UI/UX Designer",
  role: "Project Manager",
  department: "Product Design",
  shift: "Day (10:00 - 19:00)",
  isOnline: true,
};

export const memberMarcus: WorkspaceMember = {
  id: "user-2",
  name: "Marcus Vance",
  email: "marcus.v@softvence.com",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  designation: "Key Account & Sales Manager",
  role: "Sales Lead",
  department: "Client Relations & Sales",
  shift: "Day (08:00 - 17:00)",
  isOnline: true,
};

export const memberElena: WorkspaceMember = {
  id: "user-3",
  name: "Elena Rostova",
  email: "elena.r@softvence.com",
  avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
  designation: "Senior Backend Architect",
  role: "Member",
  department: "Engineering",
  shift: "Night (18:00 - 03:00)",
  isOnline: false,
  lastSeen: "2 hours ago",
};

export const memberDavid: WorkspaceMember = {
  id: "user-4",
  name: "David Kim",
  email: "david.kim@softvence.com",
  avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  designation: "QA & Automation Specialist",
  role: "Member",
  department: "Quality Assurance",
  shift: "Day (09:00 - 18:00)",
  isOnline: true,
};

export const memberAmina: WorkspaceMember = {
  id: "user-5",
  name: "Amina Al-Mansoor",
  email: "amina.m@softvence.com",
  avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  designation: "VP of Delivery & Operations",
  role: "Admin",
  department: "Management",
  isOnline: false,
  lastSeen: "Yesterday",
};

export const mockMembers: WorkspaceMember[] = [
  mockCurrentUser,
  memberSarah,
  memberMarcus,
  memberElena,
  memberDavid,
  memberAmina,
];

export const project1: ProjectWorkspaceItem = {
  id: "prj-001",
  code: "PRJ-1048",
  name: "NextGen Fintech Banking Suite",
  description: "End-to-end multi-currency neo-banking mobile app with biometric auth, peer-to-peer wire, and automated savings vaults.",
  client: {
    name: "Apex Global Capital",
    email: "finance@apexcapital.io",
    company: "Apex Holdings London",
    avatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
    platform: "Direct Contract",
  },
  status: {
    id: "st-in-progress",
    name: "In Progress",
    color: "emerald",
    isTerminal: false,
  },
  priority: {
    id: "pr-high",
    name: "High Priority",
    level: 1,
    color: "rose",
  },
  serviceLine: "Mobile & Full-Stack",
  orderSource: "Enterprise Direct",
  budget: "$48,500",
  deadline: "Nov 15, 2026",
  progress: 68,
  isPinned: true,
  unreadCount: 3,
  pendingApprovalsCount: 2,
  onlineCount: 4,
  pinnedAnnouncement: {
    id: "pin-1",
    messageId: "msg-101",
    message: "Sprint 4 Deliverables: Mobile Wallet KYC audit review is locked for this Friday 3:00 PM UTC.",
    author: "Sarah Chen",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    authorDesignation: "Lead UI/UX Designer",
    timestamp: "Today 09:15 AM",
    category: "DELIVERABLE",
  },
  pinnedAnnouncements: [
    {
      id: "pin-1",
      messageId: "msg-101",
      message: "Sprint 4 Deliverables: Mobile Wallet KYC audit review is locked for this Friday 3:00 PM UTC.",
      author: "Sarah Chen",
      authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      authorDesignation: "Lead UI/UX Designer",
      timestamp: "Today 09:15 AM",
      category: "DELIVERABLE",
    },
    {
      id: "pin-2",
      messageId: "msg-103",
      message: "Client Sync Meeting with Arthur Pendelton: Key decisions on 24/7 instant settlement rails and TestFlight staging beta.",
      author: "Marcus Vance",
      authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      authorDesignation: "Key Account & Sales Manager",
      timestamp: "Today 09:45 AM",
      category: "MEETING",
    },
    {
      id: "pin-3",
      messageId: "msg-107",
      message: "Client Outbound Package: Biometric Authentication, PSD2 compliance package uploaded for Apex compliance audit.",
      author: "Sarah Chen",
      authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      authorDesignation: "Lead UI/UX Designer",
      timestamp: "Today 10:40 AM",
      category: "ANNOUNCEMENT",
    },
  ],
  lead: memberSarah,
  teams: [
    { id: "tm-1", name: "Core Mobile Dev Team", departmentName: "Engineering", leadName: "Elena Rostova", memberCount: 4 },
    { id: "tm-2", name: "Product Experience & UI", departmentName: "Product Design", leadName: "Sarah Chen", memberCount: 3 },
    { id: "tm-3", name: "Enterprise Sales & Accounts", departmentName: "Client Relations", leadName: "Marcus Vance", memberCount: 2 },
  ],
  members: [mockCurrentUser, memberSarah, memberMarcus, memberElena, memberDavid, memberAmina],
  media: [
    {
      id: "med-1",
      title: "Wallet Dashboard High-Fidelity v4",
      url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
      type: "image",
      uploadedAt: "Oct 18, 2026",
      uploaderName: "Sarah Chen",
      dimensions: "1440x900",
    },
    {
      id: "med-2",
      title: "Biometric Login & Pin Screen Flow",
      url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
      type: "image",
      uploadedAt: "Oct 17, 2026",
      uploaderName: "Sarah Chen",
      dimensions: "1080x1920",
    },
    {
      id: "med-3",
      title: "Transaction Receipt Dark Theme Spec",
      url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      type: "image",
      uploadedAt: "Oct 15, 2026",
      uploaderName: "Marcus Vance",
      dimensions: "1280x800",
    },
  ],
  files: [
    {
      id: "fil-1",
      name: "Apex_Fintech_API_Architecture_v2.1.pdf",
      size: "4.8 MB",
      extension: "PDF",
      version: "v2.1",
      uploadedAt: "Oct 18, 2026",
      uploaderName: "Elena Rostova",
    },
    {
      id: "fil-2",
      name: "Security_Audit_Penetration_Report.docx",
      size: "1.2 MB",
      extension: "DOCX",
      version: "v1.0",
      uploadedAt: "Oct 16, 2026",
      uploaderName: "David Kim",
    },
    {
      id: "fil-3",
      name: "Design_System_Tokens_Export.json",
      size: "340 KB",
      extension: "JSON",
      version: "v4.2",
      uploadedAt: "Oct 14, 2026",
      uploaderName: "Sarah Chen",
    },
  ],
  links: [
    {
      id: "lnk-1",
      title: "Figma Master Design Specs & Components",
      url: "https://figma.com/file/apex-banking-ui-v4",
      category: "Figma",
      addedAt: "Oct 10, 2026",
      description: "Official interactive design prototype and component tokens.",
    },
    {
      id: "lnk-2",
      title: "GitHub Repository (Monorepo React Native & Go)",
      url: "https://github.com/softvence/apex-banking-app",
      category: "GitHub",
      addedAt: "Oct 11, 2026",
      description: "Production codebase with automated CI/CD pipeline.",
    },
    {
      id: "lnk-3",
      title: "Staging TestFlight Environment",
      url: "https://testflight.apple.com/join/apex-fintech-beta",
      category: "Staging",
      addedAt: "Oct 15, 2026",
      description: "Latest internal build (v0.8.4).",
    },
  ],
  milestones: [
    {
      id: "ms-1",
      title: "Biometric Auth & KYC Onboarding Verification",
      dueDate: "Oct 22, 2026",
      isCompleted: true,
      assignedTo: "Marcus Vance",
      deliverableCount: 4,
      completedAt: "Oct 20, 2026",
    },
    {
      id: "ms-2",
      title: "P2P Instant Transfers & Currency Exchange Engine",
      dueDate: "Oct 30, 2026",
      isCompleted: false,
      assignedTo: "Elena Rostova",
      deliverableCount: 6,
    },
    {
      id: "ms-3",
      title: "Automated Savings Vaults & Push Notification Trigger",
      dueDate: "Nov 08, 2026",
      isCompleted: false,
      assignedTo: "Fiamanillah",
      deliverableCount: 3,
    },
  ],
  lastMessage: {
    id: "msg-110",
    senderName: "Marcus Vance",
    text: "Drafted the client handover note for Sprint 4. Ready for Tech Lead signoff before sending to Apex Capital.",
    timestamp: "10:52 AM",
    isRead: false,
    purpose: "CLIENT_COMMUNICATION",
  },
};

export const project2: ProjectWorkspaceItem = {
  id: "prj-002",
  code: "PRJ-1052",
  name: "AI E-Commerce Recommender Engine",
  description: "Vector embedding real-time recommendation system tailored for luxury fashion retail storefronts with sub-50ms latency.",
  client: {
    name: "Maison De Luxe Paris",
    email: "tech@maisondeluxe.fr",
    company: "Luxe Brands Group",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    platform: "Fiverr Pro",
  },
  status: {
    id: "st-in-review",
    name: "In Review",
    color: "amber",
    isTerminal: false,
  },
  priority: {
    id: "pr-critical",
    name: "Critical",
    level: 0,
    color: "rose",
  },
  serviceLine: "AI & Data Engineering",
  orderSource: "Fiverr Pro Order #FO-8841",
  budget: "$32,000",
  deadline: "Nov 02, 2026",
  progress: 85,
  isPinned: true,
  unreadCount: 1,
  pendingApprovalsCount: 1,
  onlineCount: 3,
  pinnedAnnouncement: {
    id: "pin-2",
    messageId: "msg-202",
    message: "Model benchmark scoring >= 94.2% top-3 click-through prediction rate.",
    author: "Elena Rostova",
    timestamp: "Yesterday at 04:30 PM",
  },
  lead: memberDavid,
  teams: [
    { id: "tm-3", name: "Machine Learning & Ops", departmentName: "AI Research", leadName: "Elena Rostova", memberCount: 3 },
  ],
  members: [mockCurrentUser, memberDavid, memberAmina],
  media: [],
  files: [],
  links: [],
  milestones: [],
  lastMessage: {
    id: "msg-202",
    senderName: "David Kim",
    text: "Load testing passed at 12,000 req/sec with 0% dropped packets. We are ready for staging deploy!",
    timestamp: "Yesterday",
    isRead: true,
    purpose: "INTERNAL_DISCUSSION",
  },
};

export const project3: ProjectWorkspaceItem = {
  id: "prj-003",
  code: "PRJ-1039",
  name: "Enterprise Multi-Tenant SaaS Portal",
  description: "Cloud ERP and workforce allocation portal for 50,000+ distributed contractors with granular role permissions.",
  client: {
    name: "Vanguard Global Logistics",
    company: "Vanguard Logistics",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    platform: "Upwork Enterprise",
  },
  status: {
    id: "st-in-progress",
    name: "In Progress",
    color: "blue",
    isTerminal: false,
  },
  priority: {
    id: "pr-medium",
    name: "Medium Priority",
    level: 2,
    color: "amber",
  },
  serviceLine: "Enterprise Web App",
  orderSource: "Upwork Contract #UP-9923",
  budget: "$75,000",
  deadline: "Dec 20, 2026",
  progress: 42,
  unreadCount: 0,
  pendingApprovalsCount: 0,
  onlineCount: 2,
  lead: mockCurrentUser,
  teams: [],
  members: [mockCurrentUser, memberMarcus, memberAmina],
  media: [],
  files: [],
  links: [],
  milestones: [],
  lastMessage: {
    id: "msg-301",
    senderName: "Amina Al-Mansoor",
    text: "Reviewed the customer persona map and signed off on Phase 2 scope.",
    timestamp: "Oct 16",
    isRead: true,
    purpose: "INTERNAL_DISCUSSION",
  },
};

export const project4: ProjectWorkspaceItem = {
  id: "prj-004",
  code: "PRJ-1020",
  name: "Lumina Brand Identity & 3D Assets",
  description: "Complete visual rebranding, 3D product motion graphics, design guidelines, and typography system for renewable energy hardware.",
  client: {
    name: "Lumina Clean Energy",
    company: "Lumina Nordic",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    platform: "Direct Contract",
  },
  status: {
    id: "st-delivered",
    name: "Delivered",
    color: "emerald",
    isTerminal: true,
  },
  priority: {
    id: "pr-low",
    name: "Standard",
    level: 3,
    color: "slate",
  },
  serviceLine: "Branding & 3D Motion",
  orderSource: "Direct Referral",
  budget: "$19,000",
  deadline: "Oct 10, 2026",
  progress: 100,
  unreadCount: 0,
  pendingApprovalsCount: 0,
  onlineCount: 1,
  lead: memberSarah,
  teams: [],
  members: [mockCurrentUser, memberSarah],
  media: [],
  files: [],
  links: [],
  milestones: [],
  lastMessage: {
    id: "msg-401",
    senderName: "Sarah Chen",
    text: "Client approved all final deliverable packs and released escrow funds.",
    timestamp: "Oct 10",
    isRead: true,
    purpose: "INTERNAL_DISCUSSION",
  },
};

export const mockProjects: ProjectWorkspaceItem[] = [
  project1,
  project2,
  project3,
  project4,
];

export const mockMessagesByProjectId: Record<string, ChatMessage[]> = {
  "prj-001": [
    {
      id: "msg-101",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-1",
      senderName: "Sarah Chen",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Lead UI/UX Designer",
      senderRole: "Project Manager",
      isCurrentUser: false,
      text: "Good morning team! 👋 I've finalized the Sprint 4 UI specifications for the Biometric Authentication and Instant Transfer flows.",
      timestamp: "09:12 AM",
      dateGroup: "Today",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
      isPinned: true,
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "09:13 AM" },
        { userId: "user-2", userName: "Marcus Vance", userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80", userDesignation: "Key Account & Sales Manager", seenAt: "09:14 AM" },
      ],
      reactions: [
        { emoji: "🚀", count: 4, reactedByMe: true },
        { emoji: "🔥", count: 2 },
      ],
    },
    {
      id: "msg-102",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-1",
      senderName: "Sarah Chen",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Lead UI/UX Designer",
      senderRole: "Project Manager",
      isCurrentUser: false,
      text: "Here are the export design assets and architectural schema for Sprint 4 review:",
      timestamp: "09:14 AM",
      dateGroup: "Today",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "09:15 AM" },
      ],
      attachments: [
        {
          id: "att-1",
          name: "Wallet_Dashboard_v4.png",
          type: "image",
          url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
          thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&auto=format&fit=crop&q=80",
          size: "2.4 MB",
          version: "v4.0",
        },
        {
          id: "att-2",
          name: "Apex_Fintech_API_Architecture_v2.1.pdf",
          type: "file",
          size: "4.8 MB",
          version: "v2.1",
        },
      ],
    },
    {
      id: "msg-103",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-2",
      senderName: "Marcus Vance",
      senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Key Account & Sales Manager",
      senderRole: "Sales Lead",
      isCurrentUser: false,
      text: "Summary of today's 09:30 AM client sync with Apex Holdings Finance Director:",
      timestamp: "09:45 AM",
      dateGroup: "Today",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "09:46 AM" },
      ],
      meetingSummary: {
        meetingTitle: "Sprint 4 Alignment Call with Apex London",
        participants: ["Marcus Vance (Sales)", "Sarah Chen (Design)", "Arthur Pendelton (Apex Client)"],
        keyDecisions: [
          "Client approved moving wire transfers to 24/7 instant settlement rails.",
          "Agreed on soft-launching TestFlight beta build by October 28.",
          "Apex compliance team requested confirmation of ISO 27001 log archiving.",
        ],
        actionItems: [
          { task: "Attach MongoDB audit security documentation in client message", owner: "Fiamanillah", dueDate: "Today 4 PM" },
          { task: "Draft client progress handover memo for sales dispatch", owner: "Marcus Vance", dueDate: "Today 11 AM" },
        ],
      },
    },
    {
      id: "msg-104",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-current",
      senderName: "Fiamanillah",
      senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Principal Tech Lead",
      senderRole: "Tech Lead",
      isCurrentUser: true,
      replyTo: {
        id: "msg-101",
        senderName: "Sarah Chen",
        text: "Good morning team! 👋 I've finalized the Sprint 4 UI specifications for the Biometric Authentication and Instant Transfer flows.",
      },
      text: "According to ISO 27001 and PSD2 banking regulations, we should drop directly into the PIN pad after 3 failed attempts, then trigger email lock out on the 5th attempt.\n\nFurthermore, we need to enforce that all biometric signatures are encrypted at rest using AES-256-GCM hardware key stores on client devices, with audit tokens streamed asynchronously to MongoDB audit logs.",
      timestamp: "09:50 AM",
      dateGroup: "Today",
      purpose: "INTERNAL_DISCUSSION",
      variant: "default",
      seenBy: [
        { userId: "user-1", userName: "Sarah Chen", userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80", userDesignation: "Lead UI/UX Designer", seenAt: "09:51 AM" },
      ],
      reactions: [
        { emoji: "👍", count: 3, reactedByMe: true },
      ],
    },
    {
      id: "msg-105",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-3",
      senderName: "Elena Rostova",
      senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Senior Backend Architect",
      senderRole: "Member",
      isCurrentUser: false,
      text: "Milestone Deliverable Progress Update:",
      timestamp: "10:15 AM",
      dateGroup: "Today",
      purpose: "INTERNAL_DISCUSSION",
      variant: "tinted",
      deliverableUpdate: {
        title: "P2P Wire Transfer Microservice & Webhook Dispatcher",
        status: "Deployment in Staging (90% Test Coverage)",
        progress: 90,
        version: "v1.4.0-rc2",
        actionUrl: "https://github.com/softvence/apex-banking-app",
      },
    },
    {
      id: "msg-106",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "client-arthur",
      senderName: "Arthur Pendelton (Apex Capital)",
      senderAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
      isCurrentUser: false,
      isFromClient: true,
      text: "Hi Softvence Team, our compliance board has approved the architecture brief. Can you provide the staging TestFlight build with sandbox credentials so our internal testers can start on Thursday?",
      timestamp: "10:32 AM",
      dateGroup: "Today",
      purpose: "CLIENT_COMMUNICATION",
      clientDirection: "INBOUND",
      clientMessageType: "GENERAL_NOTICE",
      clientInboundRelay: {
        clientName: "Arthur Pendelton",
        clientAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
        clientCompany: "Apex Global Capital",
        platform: "Direct Portal",
        relayedBySalesName: "Marcus Vance (Sales Lead)",
        relayedAt: "10:34 AM",
      },
      reactions: [
        { emoji: "👍", count: 2, reactedByMe: true },
        { emoji: "🚀", count: 1, reactedByMe: false },
      ],
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "10:35 AM" },
        { userId: "user-1", userName: "Sarah Chen", userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80", userDesignation: "Lead UI/UX Designer", seenAt: "10:36 AM" },
      ],
    },
    {
      id: "msg-107",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-1",
      senderName: "Sarah Chen",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Lead UI/UX Designer",
      senderRole: "Project Manager",
      isCurrentUser: false,
      text: "Dear Arthur & Apex Team,\n\nWe have successfully concluded Sprint 4 milestone deliverables covering Biometric Authentication, Multi-Currency Wallet UI, and PSD2 Security compliance.\n\nAttached is the comprehensive deployment package for your audit team's sign-off.",
      timestamp: "10:40 AM",
      dateGroup: "Today",
      purpose: "CLIENT_COMMUNICATION",
      clientDirection: "OUTBOUND",
      clientMessageType: "DELIVERY",
      outboundType: "DELIVERY",
      variant: "outline",
      reactions: [
        { emoji: "👏", count: 3, reactedByMe: true },
        { emoji: "🔥", count: 2, reactedByMe: false },
      ],
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "10:41 AM" },
        { userId: "user-2", userName: "Marcus Vance", userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80", userDesignation: "Key Account & Sales Manager", seenAt: "10:42 AM" },
      ],
      approval: {
        id: "appr-107",
        status: "DISPATCHED",
        clientMessageType: "DELIVERY",
        outboundType: "DELIVERY",
        requestedBy: "Sarah Chen",
        requestedAt: "10:40 AM",
        targetClient: "Apex Global Capital",
        currentStageDwellMinutes: 0,
        totalTurnaroundMinutes: 5,
        slaTargetMinutes: 30,
        slaStatus: "ON_TRACK",
        leadApprovedBy: "Fiamanillah (Tech Lead)",
        leadApprovedAt: "10:42 AM",
        salesDispatchedBy: "Marcus Vance (Sales Lead)",
        salesDispatchedAt: "10:45 AM",
        dispatchPlatform: "Direct Portal",
        dispatchReferenceId: "APEX-DISPATCH-9912",
        auditTrail: [
          {
            id: "aud-1",
            stageName: "Draft Created",
            stageKey: "DRAFTED",
            actorName: "Sarah Chen",
            actorRole: "Lead UI/UX Designer",
            timestamp: "10:40 AM",
            durationMinutes: 0,
            notes: "Drafted Sprint 4 client delivery summary and attached compliance specs.",
          },
          {
            id: "aud-2",
            stageName: "Tech Lead Sign-off",
            stageKey: "LEAD_REVIEW",
            actorName: "Fiamanillah",
            actorRole: "Principal Tech Lead",
            timestamp: "10:42 AM",
            durationMinutes: 2,
            notes: "Approved PSD2 compliance checklist and TestFlight release notes.",
          },
          {
            id: "aud-3",
            stageName: "Dispatched to Portal",
            stageKey: "DISPATCHED",
            actorName: "Marcus Vance",
            actorRole: "Key Account & Sales Manager",
            timestamp: "10:45 AM",
            durationMinutes: 3,
            notes: "Uploaded to Apex Executive Client Portal under APEX-DISPATCH-9912.",
          },
        ],
      },
    },
    {
      id: "msg-108",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "client-arthur",
      senderName: "Arthur Pendelton (Apex Capital)",
      senderAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
      isCurrentUser: false,
      isFromClient: true,
      text: "Received the Sprint 4 deployment package. Our security auditor is reviewing the biometric token handshake now. We will confirm tranche 4 escrow once verification completes.",
      timestamp: "10:46 AM",
      dateGroup: "Today",
      purpose: "CLIENT_COMMUNICATION",
      clientDirection: "INBOUND",
      clientMessageType: "CLIENT_REPLY",
      clientInboundRelay: {
        clientName: "Arthur Pendelton",
        clientAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
        clientCompany: "Apex Global Capital",
        platform: "Direct Portal",
        relayedBySalesName: "Marcus Vance (Sales Lead)",
        relayedAt: "10:47 AM",
      },
    },
    {
      id: "msg-109",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-3",
      senderName: "Elena Rostova",
      senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Senior Backend Architect",
      senderRole: "Member",
      isCurrentUser: false,
      text: "Hi Arthur,\n\nHere is the updated TestFlight staging build URL (v0.8.4) with Sandbox API keys for the P2P transfers module. Let us know when your security team begins penetration testing.",
      timestamp: "10:48 AM",
      dateGroup: "Today",
      purpose: "CLIENT_COMMUNICATION",
      clientDirection: "OUTBOUND",
      clientMessageType: "STATUS_UPDATE",
      outboundType: "STATUS_UPDATE",
      variant: "outline",
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "10:49 AM" },
      ],
      approval: {
        id: "appr-108",
        status: "PENDING_SALES",
        clientMessageType: "STATUS_UPDATE",
        outboundType: "STATUS_UPDATE",
        requestedBy: "Elena Rostova",
        requestedAt: "10:48 AM",
        targetClient: "Apex Global Capital",
        currentStageDwellMinutes: 6,
        totalTurnaroundMinutes: 8,
        slaTargetMinutes: 30,
        slaStatus: "ON_TRACK",
        leadApprovedBy: "Fiamanillah (Tech Lead)",
        leadApprovedAt: "10:50 AM",
        auditTrail: [
          {
            id: "aud-4",
            stageName: "Draft Created",
            stageKey: "DRAFTED",
            actorName: "Elena Rostova",
            actorRole: "Senior Backend Architect",
            timestamp: "10:48 AM",
            durationMinutes: 0,
            notes: "Prepared staging keys and TestFlight link for client penetration testing.",
          },
          {
            id: "aud-5",
            stageName: "Tech Lead Sign-off",
            stageKey: "LEAD_REVIEW",
            actorName: "Fiamanillah",
            actorRole: "Principal Tech Lead",
            timestamp: "10:50 AM",
            durationMinutes: 2,
            notes: "Verified API sandbox rate limits are configured.",
          },
        ],
      },
    },
    {
      id: "msg-110",
      projectId: "prj-001",
      projectCode: "PRJ-1048",
      senderId: "user-2",
      senderName: "Marcus Vance",
      senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Key Account & Sales Manager",
      senderRole: "Sales Lead",
      isCurrentUser: false,
      text: "Hello Apex Team,\n\nWe have scheduled the milestone invoice release for Sprint 4. Please verify receipt of the wire transfer microservice documentation before approving Escrow tranche #4.",
      timestamp: "10:52 AM",
      dateGroup: "Today",
      purpose: "CLIENT_COMMUNICATION",
      clientDirection: "OUTBOUND",
      clientMessageType: "PAYMENT_ESCROW",
      outboundType: "PAYMENT_ESCROW",
      variant: "outline",
      seenBy: [
        { userId: "user-current", userName: "Fiamanillah", userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80", userDesignation: "Principal Tech Lead", seenAt: "10:53 AM" },
      ],
      approval: {
        id: "appr-109",
        status: "PENDING_LEAD",
        clientMessageType: "PAYMENT_ESCROW",
        outboundType: "PAYMENT_ESCROW",
        requestedBy: "Marcus Vance",
        requestedAt: "10:52 AM",
        targetClient: "Apex Global Capital",
        currentStageDwellMinutes: 14,
        slaTargetMinutes: 30,
        slaStatus: "ON_TRACK",
        auditTrail: [
          {
            id: "aud-6",
            stageName: "Draft Created",
            stageKey: "DRAFTED",
            actorName: "Marcus Vance",
            actorRole: "Key Account & Sales Manager",
            timestamp: "10:52 AM",
            durationMinutes: 0,
            notes: "Drafted escrow release notification for Arthur Pendelton.",
          },
        ],
      },
    },
  ],
  "prj-002": [
    {
      id: "msg-201",
      projectId: "prj-002",
      projectCode: "PRJ-1052",
      senderId: "user-3",
      senderName: "Elena Rostova",
      senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Senior Backend Architect",
      senderRole: "Member",
      isCurrentUser: false,
      text: "The Pinecone vector indexing job completed with 450,000 luxury product catalog embeddings.",
      timestamp: "Yesterday at 03:20 PM",
      dateGroup: "Yesterday",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
    },
    {
      id: "msg-202",
      projectId: "prj-002",
      projectCode: "PRJ-1052",
      senderId: "user-4",
      senderName: "David Kim",
      senderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "QA & Automation Specialist",
      senderRole: "Member",
      isCurrentUser: false,
      text: "Load testing passed at 12,000 req/sec with 0% dropped packets. We are ready for staging deploy!",
      timestamp: "Yesterday at 04:12 PM",
      dateGroup: "Yesterday",
      purpose: "INTERNAL_DISCUSSION",
      variant: "tinted",
      isPinned: true,
      reactions: [
        { emoji: "🎉", count: 4, reactedByMe: true },
      ],
    },
  ],
  "prj-003": [
    {
      id: "msg-301",
      projectId: "prj-003",
      projectCode: "PRJ-1039",
      senderId: "user-5",
      senderName: "Amina Al-Mansoor",
      senderAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "VP of Delivery & Operations",
      senderRole: "Admin",
      isCurrentUser: false,
      text: "Reviewed the customer persona map and signed off on Phase 2 scope.",
      timestamp: "Oct 16, 2026",
      dateGroup: "Oct 16, 2026",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
    },
  ],
  "prj-004": [
    {
      id: "msg-401",
      projectId: "prj-004",
      projectCode: "PRJ-1020",
      senderId: "user-1",
      senderName: "Sarah Chen",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderDesignation: "Lead UI/UX Designer",
      senderRole: "Project Manager",
      isCurrentUser: false,
      text: "Client approved all final deliverable packs and released escrow funds.",
      timestamp: "Oct 10, 2026",
      dateGroup: "Oct 10, 2026",
      purpose: "INTERNAL_DISCUSSION",
      variant: "secondary",
    },
  ],
};

export const mockHistoricalOlderMessages: ChatMessage[] = [
  {
    id: "msg-098",
    projectId: "prj-001",
    projectCode: "PRJ-1048",
    senderId: "user-1",
    senderName: "Sarah Chen",
    senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    senderDesignation: "Lead UI/UX Designer",
    senderRole: "Project Manager",
    isCurrentUser: false,
    text: "Welcome team to the Apex Banking App overhaul! Here is the finalized Sprint 1-4 roadmap with milestone deliverable dates.",
    timestamp: "09:00 AM",
    dateGroup: "Oct 01, 2026",
    purpose: "INTERNAL_DISCUSSION",
    attachments: [
      {
        id: "att-hist-1",
        name: "Apex_Banking_Architecture_Roadmap.pdf",
        type: "file",
        size: "4.2 MB",
        version: "v1.0",
      },
    ],
  },
  {
    id: "msg-099",
    projectId: "prj-001",
    projectCode: "PRJ-1048",
    senderId: "user-current",
    senderName: "Fiamanillah",
    senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    senderDesignation: "Principal Tech Lead",
    senderRole: "Tech Lead",
    isCurrentUser: true,
    text: "I have configured the GitHub enterprise monorepo and connected CI/CD webhook pipelines with staging automatic builds.",
    timestamp: "09:15 AM",
    dateGroup: "Oct 01, 2026",
    purpose: "INTERNAL_DISCUSSION",
    variant: "default",
    reactions: [{ emoji: "🚀", count: 4, reactedByMe: true }],
  },
  {
    id: "msg-100",
    projectId: "prj-001",
    projectCode: "PRJ-1048",
    senderId: "client-arthur",
    senderName: "Arthur Pendelton (Apex Capital)",
    senderAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
    isCurrentUser: false,
    isFromClient: true,
    text: "Hello everyone, excited to kick off Sprint 1 with the Softvence engineering team! Our compliance auditor has signed the non-disclosure agreements.",
    timestamp: "09:30 AM",
    dateGroup: "Oct 01, 2026",
    purpose: "CLIENT_COMMUNICATION",
    clientDirection: "INBOUND",
    clientMessageType: "GENERAL_NOTICE",
    clientInboundRelay: {
      clientName: "Arthur Pendelton",
      clientAvatar: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
      clientCompany: "Apex Global Capital",
      platform: "Direct Portal",
      relayedBySalesName: "Marcus Vance (Sales Lead)",
      relayedAt: "09:32 AM",
    },
    reactions: [{ emoji: "🤝", count: 3, reactedByMe: true }],
  },
];
