name: dev
variables:
  - name: baseUrl
    value: http://localhost:3030
    description: ""
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTczNTlkZC05Yzk0LTRjZDgtOGM0Ni00NWVmMTEzYzg5MDgiLCJzeXN0ZW1Sb2xlIjoiU3VwZXJBZG1pbiIsImRlc2lnbmF0aW9uSWQiOiIwYmFmNjIyZS00ZTM1LTRkNTktYWNhOS1lYzhkZWYyODNjMTIiLCJpYXQiOjE3ODY2MjcxMjcsImV4cCI6MTc4NjYyODAyNywiaXNzIjoiaWduaXRvci1hcHAifQ.Tv_81UsR1IG_VRFA6kETvhwbdpgEK4kW3VAC331Wbpw
    description: ""
