name: dev
variables:
  - name: baseUrl
    value: http://localhost:3030
  - name: email
    value: superadmin@agency.local
  - name: password
    value: SuperSecretDevPassword123!
  - name: inviteToken
    value: sample_invite_token_here
  - name: resetToken
    value: sample_reset_token_here
  - name: userId
    value: sample_user_id_here
  - name: auditLogId
    value: sample_audit_log_id_here
  - name: designationId
    value: sample_designation_id_here
