// src/Modules/Projects/projects.manifest.ts

import type { PermissionManifestItem } from "@/core/permissions/permission.types";
import { SCOPE_PRESETS } from "@/core/permissions/scopePresets";

export const projectsPermissions: PermissionManifestItem[] = [
  {
    code: "project.view",
    module: "Projects",
    description: "View project details, milestones, and assigned rosters",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
  },
  {
    code: "project.create",
    module: "Projects",
    description: "Create new projects and allocate initial teams",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
    dependsOn: ["organization.team.view", "organization.department.view"],
  },
  {
    code: "project.edit",
    module: "Projects",
    description: "Edit project general details, status, and deadlines",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.delete",
    module: "Projects",
    description: "Soft-delete projects from active records",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.reassign",
    module: "Projects",
    description: "Reassign project primary and secondary team allocations",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
    dependsOn: ["organization.team.view"],
  },
  {
    code: "project.manage_members",
    module: "Projects",
    description: "Assign and unassign individual members and roles to projects",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
    dependsOn: ["auth.user.view"],
  },
  {
    code: "project.component.manage",
    module: "Projects",
    description: "Create, modify, and assign project components and sub-tasks",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.client.view",
    module: "Projects",
    description: "View sensitive project client identity, company names, and contact information",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.financial.view",
    module: "Projects",
    description: "View sensitive project contract values, billing milestones, and order sheets",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.financial.edit",
    module: "Projects",
    description: "Modify project contract values and internal order sheet URLs",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.financial.view", "project.view"],
  },
  {
    code: "project.chat.view",
    module: "Projects",
    description: "View project internal discussions and communication history",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
  },
  {
    code: "project.chat.send",
    module: "Projects",
    description: "Send internal discussion messages, voice notes, and reactions",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.view"],
    dependsOn: ["storage.upload", "storage.view"],
  },
  {
    code: "project.chat.send_client",
    module: "Projects",
    description: "Draft outbound client communications and relay inbound client messages",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.chat.send", "project.view"],
    dependsOn: ["storage.upload", "storage.view"],
  },
  {
    code: "project.chat.pin",
    module: "Projects",
    description: "Pin and unpin important messages to the project banner",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.view"],
  },
  {
    code: "project.chat.manage_types",
    module: "Projects",
    description: "Create and configure custom message types for project conversations",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.view"],
  },
  {
    code: "project.approval.lead_review",
    module: "Projects",
    description: "Review and approve/reject drafted outbound client communications as Lead",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.view"],
  },
  {
    code: "project.approval.sales_dispatch",
    module: "Projects",
    description: "Dispatch approved client messages to external platforms (Fiverr, Upwork, Slack, etc.)",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.chat.view", "project.view"],
  },
  {
    code: "project.collateral.manage",
    module: "Projects",
    description: "Create, update, and manage project milestones, links, and collateral files",
    supportedScopes: SCOPE_PRESETS.PROJECT_HIERARCHICAL,
    implies: ["project.view"],
    dependsOn: ["storage.upload", "storage.view", "storage.delete"],
  },
];

export default projectsPermissions;
