// src/Modules/Projects/ProjectDTO.ts

export {
  createProjectSchema,
  updateProjectSchema,
  assignProjectTeamSchema,
  assignProjectMemberSchema,
  updateProjectMemberSchema,
  createProjectComponentSchema,
  updateProjectComponentSchema,
  assignComponentMemberSchema,
  createQuickClientSchema,
  createQuickProfileSchema,
  createQuickPlatformSchema,
  createQuickServiceLineSchema,
  createQuickStatusSchema,
  createQuickOrderSourceSchema,
  type CreateProjectDTO,
  type UpdateProjectDTO,
  type AssignProjectTeamDTO,
  type AssignProjectMemberDTO,
  type UpdateProjectMemberDTO,
  type CreateProjectComponentDTO,
  type UpdateProjectComponentDTO,
  type AssignComponentMemberDTO,
  type CreateQuickClientDTO,
  type CreateQuickProfileDTO,
  type CreateQuickPlatformDTO,
  type CreateQuickServiceLineDTO,
  type CreateQuickStatusDTO,
  type CreateQuickOrderSourceDTO,
  type ProjectCapabilities,
  type ProjectItem,
  type ProjectDetailItem,
  type ProjectStats,
  type ProjectLookups,
  type ProjectStatusItem,
  type PlatformItem,
  type ProfileItem,
  type ClientItem,
  type ServiceLineItem,
  type OrderSourceItem,
  type ProjectParentSummary,
  type ProjectParentCandidate,
} from "@workspace/shared";
