// src/Modules/Projects/ProjectDTO.ts

export {
  createProjectSchema,
  updateProjectSchema,
  assignProjectTeamSchema,
  assignProjectMemberSchema,
  updateProjectMemberSchema,
  createProjectComponentSchema,
  updateProjectComponentSchema,
  assignComponentMemberSchema,
  createQuickClientSchema,
  createQuickProfileSchema,
  createQuickPlatformSchema,
  createQuickServiceLineSchema,
  createQuickStatusSchema,
  createQuickOrderSourceSchema,
  createProjectMessageSchema,
  toggleReactionSchema,
  markMessagesSeenSchema,
  leadApproveSchema,
  salesDispatchSchema,
  requestRevisionSchema,
  createMessageTypeSchema,
  updateMessageTypeSchema,
  createProjectMilestoneSchema,
  updateProjectMilestoneSchema,
  createProjectLinkSchema,
  type CreateProjectDTO,
  type UpdateProjectDTO,
  type AssignProjectTeamDTO,
  type AssignProjectMemberDTO,
  type UpdateProjectMemberDTO,
  type CreateProjectComponentDTO,
  type UpdateProjectComponentDTO,
  type AssignComponentMemberDTO,
  type CreateQuickClientDTO,
  type CreateQuickProfileDTO,
  type CreateQuickPlatformDTO,
  type CreateQuickServiceLineDTO,
  type CreateQuickStatusDTO,
  type CreateQuickOrderSourceDTO,
  type CreateProjectMessageDTO,
  type ToggleReactionDTO,
  type MarkMessagesSeenDTO,
  type LeadApproveDTO,
  type SalesDispatchDTO,
  type RequestRevisionDTO,
  type CreateMessageTypeDTO,
  type UpdateMessageTypeDTO,
  type CreateProjectMilestoneDTO,
  type UpdateProjectMilestoneDTO,
  type CreateProjectLinkDTO,
  type ProjectCapabilities,
  type ProjectItem,
  type ProjectDetailItem,
  type ProjectStats,
  type ProjectLookups,
  type ProjectStatusItem,
  type PlatformItem,
  type ProfileItem,
  type ClientItem,
  type ServiceLineItem,
  type OrderSourceItem,
  type ProjectParentSummary,
  type ProjectParentCandidate,
  type ProjectMessageItem,
  type ProjectMessageCapabilities,
  type MessageReactionItem,
  type MessageReadReceiptItem,
  type ApprovalWorkflowItem,
  type ApprovalStageAuditItem,
  type MessageTypeItem,
  type ProjectMilestoneItem,
  type ProjectLinkItem,
  type ProjectWorkspaceItem,
  type WorkspaceMemberItem,
  type ProjectTeamSummaryItem,
} from "@workspace/shared";

